<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-05-11 00:41:36 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'Track' documents,
then the 'TrackDocument' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Track\Base;

/**
 * Serves as the base class to the 'Track' document skeleton.
 */
abstract class TrackDocument extends \Honeybee\Core\Dat0r\Document
{ 
    /**
     * Returns an 'Track' document's title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->getValue('title');
    }

    /**
     * Sets an 'Track' document's title.
     *
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->setValue('title', $title);
    }

    /**
     * Returns an 'Track' document's description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->getValue('description');
    }

    /**
     * Sets an 'Track' document's description.
     *
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->setValue('description', $description);
    }

    /**
     * Returns an 'Track' document's duration.
     *
     * @return int
     */
    public function getDuration()
    {
        return $this->getValue('duration');
    }

    /**
     * Sets an 'Track' document's duration.
     *
     * @param int $duration
     */
    public function setDuration($duration)
    {
        $this->setValue('duration', $duration);
    }

    /**
     * Returns an 'Track' document's audioFile.
     *
     * @return array
     */
    public function getAudiofile()
    {
        return $this->getValue('audioFile');
    }

    /**
     * Sets an 'Track' document's audioFile.
     *
     * @param array $audioFile
     */
    public function setAudiofile($audioFile)
    {
        $this->setValue('audioFile', $audioFile);
    }

    /**
     * Returns an 'Track' document's bitRate.
     *
     * @return int
     */
    public function getBitrate()
    {
        return $this->getValue('bitRate');
    }

    /**
     * Sets an 'Track' document's bitRate.
     *
     * @param int $bitRate
     */
    public function setBitrate($bitRate)
    {
        $this->setValue('bitRate', $bitRate);
    }

    /**
     * Returns an 'Track' document's sampleRate.
     *
     * @return int
     */
    public function getSamplerate()
    {
        return $this->getValue('sampleRate');
    }

    /**
     * Sets an 'Track' document's sampleRate.
     *
     * @param int $sampleRate
     */
    public function setSamplerate($sampleRate)
    {
        $this->setValue('sampleRate', $sampleRate);
    }

    /**
     * Returns an 'Track' document's coverImages.
     *
     * @return array
     */
    public function getCoverimages()
    {
        return $this->getValue('coverImages');
    }

    /**
     * Sets an 'Track' document's coverImages.
     *
     * @param array $coverImages
     */
    public function setCoverimages($coverImages)
    {
        $this->setValue('coverImages', $coverImages);
    }

    /**
     * Returns an 'Track' document's meta.
     *
     * @return array
     */
    public function getMeta()
    {
        return $this->getValue('meta');
    }

    /**
     * Sets an 'Track' document's meta.
     *
     * @param array $meta
     */
    public function setMeta($meta)
    {
        $this->setValue('meta', $meta);
    }

    /**
     * Returns an 'Track' document's workflowTicket.
     *
     * @return WorkflowTicketModule
     */
    public function getWorkflowticket()
    {
        return $this->getValue('workflowTicket');
    }

    /**
     * Sets an 'Track' document's workflowTicket.
     *
     * @param WorkflowTicketModule $workflowTicket
     */
    public function setWorkflowticket($workflowTicket)
    {
        $this->setValue('workflowTicket', $workflowTicket);
    }
}
