<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-05-11 00:41:36 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Track' module,
then the 'TrackModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Track\Base;

/**
 * Serves as the base class to the 'Track'' module skeleton.
 */
abstract class TrackModule extends \Honeybee\Core\Dat0r\Module
{
    /**
     * Creates a new TrackModule instance.
     */
    protected function __construct()
    {
        parent::__construct('Track', array( 
            \Dat0r\Core\Runtime\Field\TextField::create('title'), 
            \Dat0r\Core\Runtime\Field\TextareaField::create('description'), 
            \Dat0r\Core\Runtime\Field\IntegerField::create('duration'), 
            \Dat0r\Core\Runtime\Field\IntegerCollectionField::create('audioFile', array(                  
                'acts_as_assets_field' => 'true',  
            )), 
            \Dat0r\Core\Runtime\Field\IntegerField::create('bitRate'), 
            \Dat0r\Core\Runtime\Field\IntegerField::create('sampleRate'), 
            \Dat0r\Core\Runtime\Field\IntegerCollectionField::create('coverImages', array(                  
                'acts_as_assets_field' => 'true',  
            )), 
            \Dat0r\Core\Runtime\Field\KeyValueField::create('meta', array(                  
                'constraints' => array('value_type' => 'dynamic',),  
            )), 
            \Dat0r\Core\Runtime\Field\AggregateField::create('workflowTicket', array(                  
                'aggregate_module' => 'Honeybee\\Domain\\Track\\WorkflowTicketModule',  
            )), 
        ), array(             
            'prefix' => 'track',               
            'identifier_field' => 'identifier',               
            'baseModule' => '\\Honeybee\\Core\\Dat0r\\Module',               
            'baseDocument' => '\\Honeybee\\Core\\Dat0r\\Document',   
        ));
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return 'Honeybee\Domain\Track\TrackDocument';
    }
}
