<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-05-10 23:39:47 and allows to alter the behaviour of 'PluginResult' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Track;

/**
 * A PluginResult reflects a state resulting from executing a workflow plugin.
 */
class PluginResultDocument extends \Honeybee\Domain\Track\Base\PluginResultDocument
{
    
}
