<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-05-10 23:39:47 and allows to alter the behaviour of 'Track' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Track;

/**
 * Holds the structure definition for Track documents.
 */
class TrackDocument extends \Honeybee\Domain\Track\Base\TrackDocument
{
    
}
