<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-05-10 23:39:47 and allows to alter the behaviour of the 'WorkflowTicket' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Track;

/**
 * The WorkflowTicketModule class reflects the declared structure of the 'WorkflowTicket' entity.
 * It holds the meta data necessary to manage/initiate 'WorkflowTicketDocument' lifecycles.
 */
class WorkflowTicketModule extends \Honeybee\Domain\Track\Base\WorkflowTicketModule
{
    
}
